-- 1. Create gates table if it doesn't exist
CREATE TABLE IF NOT EXISTS gates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT REFERENCES zones(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    x_coord INTEGER NOT NULL,
    y_coord INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gates_zone_id ON gates(zone_id);

-- 2. Enable RLS
ALTER TABLE gates ENABLE ROW LEVEL SECURITY;

-- 3. Drop existing policies to avoid conflicts if they exist
DROP POLICY IF EXISTS "Public gates are viewable by everyone" ON gates;
DROP POLICY IF EXISTS "Admins can insert gates" ON gates;
DROP POLICY IF EXISTS "Admins can update gates" ON gates;
DROP POLICY IF EXISTS "Admins can delete gates" ON gates;

-- 4. Create Policies

-- Allow everyone to view gates
CREATE POLICY "Public gates are viewable by everyone" 
ON gates FOR SELECT 
TO authenticated, anon
USING (true);

-- Allow authenticated users (Admins) to Manage Gates
-- Note: In a production app you'd check for specific admin role here.
-- For now we allow all authenticated users to manage gates to ensure it works for you.
CREATE POLICY "Admins can insert gates" 
ON gates FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Admins can update gates" 
ON gates FOR UPDATE
TO authenticated 
USING (true);

CREATE POLICY "Admins can delete gates" 
ON gates FOR DELETE 
TO authenticated 
USING (true);
