-- Enable UUID extension if needed (though we use integer/string IDs here based on requirements, nice to have)
create extension if not exists "uuid-ossp";

-- Users Table
-- Stores auth profile linked to Supabase Auth (or standalone if utilizing custom auth logic, but usually we link to auth.users)
-- Requirement: Student/Employee ID, Email, Password Hash.
create table public.users (
  id uuid references auth.users on delete cascade not null primary key, -- Linked to Supabase Auth
  student_id text unique not null,
  email text not null,
  password_hash text, -- Optional if using Supabase Auth, but kept as per schema request
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Zones Table
-- Parking zones (Building or Outdoor)
create table public.zones (
  id bigint generated by default as identity primary key,
  name text not null,
  type text check (type in ('building', 'outdoor')) not null,
  total_floors integer default 1 not null,
  gate_x integer, -- Coordinate for gate/entrance
  gate_y integer,
  image_url text, -- For reference if needed later
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Spots Table
-- Individual parking spots
create table public.spots (
  id bigint generated by default as identity primary key,
  zone_id bigint references public.zones(id) on delete cascade not null,
  spot_number text not null, -- e.g., "A-101"
  floor_level integer default 0 not null, -- 0 for ground, 1, 2, 3...
  status integer default 0 check (status in (0, 1, 2)) not null, -- 0: Available, 1: Reserved, 2: Occupied
  x_coord integer not null,
  y_coord integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Realtime subscription setup
-- Enable publication for 'spots' table to listen to changes
alter publication supabase_realtime add table public.spots;
