-- Create gates table
CREATE TABLE IF NOT EXISTS gates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT REFERENCES zones(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    x_coord INTEGER NOT NULL,
    y_coord INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_gates_zone_id ON gates(zone_id);

-- Optional: Migrate existing gates
-- INSERT INTO gates (zone_id, name, x_coord, y_coord)
-- SELECT id, 'Main Gate', gate_x, gate_y FROM zones WHERE gate_x IS NOT NULL;
